language: python
python:
  - "2.7"
cache: pip
install:
  - pip install -r requirements.txt
script:
  - python ex1.py
  - python ex2.py
  - python ex3.py
  - python ex4.py
  - python ex5.py
  - python ex6.py
  - python ex7.py
  - python ex8.py
  - python ex9.py
  - python ex10.py 
  - python ex11.py < testing.txt
  - python ex12.py < testing.txt
  - python ex13.py < ex13_input.txt
  - python ex14.py Sam < ex14_answer.txt
  - python ex15.py ex15_sample.txt < ex15_answer.txt
  - python ex16.py test.txt < ex16_answer.sh
  - python ex17.py test.txt new_file.txt < ex17_answer.sh
  - python ex18.py
  - python ex19.py
  - python ex20.py test.txt
  - python ex21.py
  - python ex24.py
  - python ex25.py

