language: python
python:
  - "2.7"
cache: pip
install:
  - pip install -r requirements.txt
script:
  - python exercises/ex1.py
  - python exercises/ex2.py
  - python exercises/ex3.py
  - python exercises/ex4.py
  - python exercises/ex5.py
  - python exercises/ex6.py
  - python exercises/ex7.py
  - python exercises/ex8.py
  - python exercises/ex9.py
  - python exercises/ex10.py 
  - python exercises/ex11.py < answers/testing.txt
  - python exercises/ex12.py < answers/testing.txt
  - python exercises/ex13.py < answers/ex13_input.txt
  - python exercises/ex14.py Sam < answers/ex14_answer.txt
  - python exercises/ex15.py ex15_sample.txt < answers/ex15_answer.txt
  - python exercises/ex18.py
  - python exercises/ex19.py
  - python exercises/ex20.py answers/testing.txt
  - python exercises/ex21.py
  - python exercises/ex24.py
  - python exercises/ex25.py
