language: python
python:
  - "2.7"
cache: pip
install:
  - pip install -r requirements.txt
script:
  - python exercises/ex1.py
  - python exercises/ex2.py
  - python exercises/ex3.py
  - python exercises/ex4.py
  - python exercises/ex5.py
  - python exercises/ex6.py
  - python exercises/ex7.py
  - python exercises/ex8.py
  - python exercises/ex9.py
  - python exercises/ex10.py 
  - python exercises/ex11.py < answers/testing.txt
  - python exercises/ex12.py < answers/testing.txt
  - python exercises/ex13.py < answers/ex13_input.txt
  - python exercises/ex14.py Sam < answers/ex14_answer.txt
  - python exercises/ex15.py < answers/ex15_sample.txt < ex15_answer.txt
  - python exercises/ex16.py test.txt < bash_files/ex16_answer.sh
  - python exercises/ex17.py test.txt new_file.txt < bash_files ex17_answer.sh
  - python exercise/ex18.py
  - python exercise/ex19.py
  - python exercise/ex20.py/answers test.txt
  - python exercise/ex21.py
  - python exercise/ex24.py
  - python exercise/ex25.py

